###############################################################################
# RELEASE
###############################################################################

name: ✅ Tests and check for updates

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  GITHUB_TOKEN: ${{ github.token }}
  NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

###############################################################################
# JOBS
###############################################################################

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:

      #########################################################################
      # INIT
      #########################################################################

      - name: ⬇️🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
      - name: ⬇️🛎 Checkout
        uses: actions/checkout@v4
      - name: ⬇️🥡 Install pnpm
        uses: pnpm/action-setup@v4
      - name: ⬇️🟢 Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: 'pnpm'

      - name: 🐙😺 Check GitHub API Rate Limit
        id: rate_limit
        run: |
          response=$(gh api rate_limit)
          limit=$(echo $response | jq -r '.resources.core.limit')
          remaining=$(echo $response | jq -r '.resources.core.remaining')
          echo "GitHub API Rate Limit: $remaining/$limit"

          if [ "$remaining" -lt 10 ]; then
              exit 1
          fi
        env:
            GH_TOKEN: ${{ env.GITHUB_TOKEN }}

      - name: ⬇️📦 Install dependencies
        run: pnpm install --no-frozen-lockfile --ignore-scripts


      #########################################################################
      # BUILD
      #########################################################################

      - name: 🏗 Build packages
        run: pnpm build

      #########################################################################
      # TEST
      #########################################################################

      - name: ✅ Run [e2e & unit] tests
        run: pnpm test

      #########################################################################
      # EXIT IF IS PULL REQUEST
      #########################################################################

      - name: 🚪 Exit here if is pull request
        if: github.event_name == 'pull_request'
        run: |
          echo "Pull request detected, exiting..."
          exit 0
        env:
          GITHUB_TOKEN: ${{env.GITHUB_TOKEN }}

      #########################################################################
      #########################################################################
      # UPDATE VERSIONS
      #########################################################################
      #########################################################################

      - name: 🌥 Deploy in cloudflare pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          projectName: "dovenv"
          directory: 'build/docs'
          wranglerVersion: '3'


      - name: ℹ️➡️ Check for changes in package.json
        run: |
          git fetch origin main
          git diff --name-only HEAD origin/main | grep 'package.json' || echo "No changes in package.json"
        continue-on-error: true
        id: check_package_json
      - name: ℹ️🐙😺➡️ Update repo info
        if: steps.check_package_json.outputs.stdout != 'No changes in package.json'
        run: pnpm . gh repo-info
        continue-on-error: true

###############################################################################
